[package]
name = "atomcad-gui"
version = "0.1.0"
publish = false
authors = ["Machine Phase Systems <hello@machinephase.systems>"]
license = "MPL-2.0"
edition = "2021"

[dependencies]
# Logging
log = { workspace = true }
# GUI
winit = { workspace = true }
# Utilities
bitflags = "2.6"

# macOS platform support
[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"
